apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    component: client
spec:
  replicas: 2
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: kodega2016/multi-client
          ports:
            - containerPort: 3000
