apiVersion: v1
kind: Service
metadata:
  name: client-loadbalancer-service
spec:
  selector:
    component: client
  ports:
    - name: client
      protocol: TCP
      targetPort: 3000
      port: 80
